<a href="https://colab.research.google.com/github/P-Pin/6m-data-1.6-intro-numpy/blob/main/Numpy_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# [DEMO] Casting arrays
arr = np.array([3.7, -1.2, 0.5, 12.9])
print("Original:", arr)
print("Casted to int32:", arr.astype(np.int32))

Original: [ 3.7 -1.2  0.5 12.9]
Casted to int32: [ 3 -1  0 12]


In [5]:
# [DEMO] Creating arrays from sequences
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)

data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)

print(f"Array 2:\n{arr2}")
print(f"Shape: {arr2.shape}, Dtype: {arr2.dtype}, Dimensions: {arr2.ndim}")

Array 2:
[[1 2 3 4]
 [5 6 7 8]]
Shape: (2, 4), Dtype: int64, Dimensions: 2


In [9]:
# -- Exercise 1 -- FLOAT32 vs FLOAT64

import numpy as np

arr = np.ones((3, 4))
print(arr)

arr_float32 = arr.astype(np.float32)
print(arr_float32)
print(arr_float32.dtype)

str_numbers = np.array(['1.25', '-9.6', '42'])
float_numbers = str_numbers.astype(float)

print(float_numbers)
print(float_numbers.dtype)


# -- FINAL RECAP --
# -- creating arrays --
# -- controlling data types --
# -- converting strings to numbers --
# -- below recap final code --

# import numpy as np

# arr = np.ones((3, 4)).astype(np.float32)

# str_numbers = np.array(['1.25', '-9.6', '42'])
# float_numbers = str_numbers.astype(float)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
float32
[ 1.25 -9.6  42.  ]
float64


In [3]:
import numpy as np
my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

#check the length of my array
print(f"length of my_arr: {len(my_arr)}")

#print first 5 elements in array

#slicing syntax: arry[start:end:step], end index is exclusive
print ("first 5 elements of my_arr:", my_arr[:5])

#print last 5 elements in array
print ("last 5 elements of my_arr:", my_arr[-5:])
my_list = list(range(1_000_000))

print("NumPy Vectorized Multiplication (my_arr * 2):")
%timeit my_arr2 = my_arr * 2

print("\nPython List Comprehension ([x * 2 for x in my_list]):")
%timeit my_list2 = [x * 2 for x in my_list]

length of my_arr: 1000000
first 5 elements of my_arr: [0 1 2 3 4]
last 5 elements of my_arr: [999995 999996 999997 999998 999999]
NumPy Vectorized Multiplication (my_arr * 2):
1.43 ms ± 176 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

Python List Comprehension ([x * 2 for x in my_list]):
57.2 ms ± 1.94 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [10]:
# [DEMO] Arithmetic & Broadcasting
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print("Element-wise multiplication (arr * arr):\n", arr * arr)
print("\nBroadcasting scalar (1 / arr):\n", 1 / arr)

Element-wise multiplication (arr * arr):
 [[ 1.  4.  9.]
 [16. 25. 36.]]

Broadcasting scalar (1 / arr):
 [[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


In [11]:
# [DEMO] Slicing views
arr = np.arange(10)
arr_slice = arr[5:8]
arr_slice[1] = 12345
print("Original array modified via slice:", arr)

# [DEMO] 2D Slicing
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nFirst two rows, columns 1 onwards:\n", arr2d[:2, 1:])

Original array modified via slice: [    0     1     2     3     4     5 12345     7     8     9]

First two rows, columns 1 onwards:
 [[2 3]
 [5 6]]


In [18]:
# -- Exercise 2 - Logic of Slicing --
#Select the first column of arr2d using a slice.
#Set all values in the second row to 0.
#Socratic Prompt: How does arr2d[1] differ from arr2d[1, :]?
#(Hint: check shapes)

import numpy as np

arr2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])


#Select the first column using a slice

first_col = arr2d[:, 0]
print(first_col)
print(first_col.shape)

#Set all values in the second row to 0
arr2d[1, :] = 0
print(arr2d)

#Socratic Prompt: How does arr2d[1] differ from arr2d[1, :]?

print(arr2d[1])
print(arr2d[1, :])

print(arr2d[1].shape)
print(arr2d[1, :].shape)

#What you’ll observe:
#Both return the same values
#Both have the same shape: (3,)

#So… what’s the difference?
#In NumPy, there is no difference here.
#arr2d[1] is just shorthand for arr2d[1, :].

#The difference appears when you compare with:

arr2d[1:2, :]

#Which has shape:

(1, 3)

#Key takeaway (important):

# arr2d[1] → 1D array

# arr2d[1, :] → 1D array

# arr2d[1:2, :] → 2D array (row preserved)

#This distinction becomes critical in:

#Linear algebra
#Broadcasting
#Machine learning models


[1 4 7]
(3,)
[[1 2 3]
 [0 0 0]
 [7 8 9]]
[0 0 0]
[0 0 0]
(3,)
(3,)


(1, 3)

In [19]:

#Part 5 : Boolean Indexing
#Like arithmetic operations, comparisons (such as ==) with arrays are vectorized.
#This yields a boolean array which can be used to filter data.


# [DEMO] Filtering scores
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
scores = np.array([[75, 80], [85, 90], [95, 100], [100, 77], [85, 92], [95, 80], [72, 80]])

# A mask is a boolean array indicating which elements to select / meet a condition.

bob_mask = (names == 'Bob')
print("Mask:", bob_mask)
print("Bob's scores:\n", scores[bob_mask])

Mask: [ True False False  True False False False]
Bob's scores:
 [[ 75  80]
 [100  77]]


In [23]:

#Exercise 3 : Boolean Indexing - Complex Filtering

#Select all scores where the name is NOT
#Select scores for 'Bob' or 'Will' using the | operator.
#Find all scores less than 80 and set them to 0.


#Example data (names + scores)

import numpy as np

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe'])
scores = np.array([85, 92, 78, 88, 95, 73])

#Think of these as parallel arrays — same index means same person.


#1️⃣ Select all scores where the name is NOT 'Bob'

mask = names != 'Bob'
result = scores[mask]
print(result)

#What’s happening (step by step)

names != 'Bob'

#Produces a boolean mask: (graphql output)
# -->  [False  True  True False  True  True]

#Then:

scores[mask]

#Keeps values where the mask is True.
# --> [92 78 95 73]

#Rule:
#Boolean True → keep
#Boolean False → drop

#2️⃣ Select scores for 'Bob' OR 'Will' using |
#Important rule first
#You must use parentheses with | and &.

mask = (names == 'Bob') | (names == 'Will')
result = scores[mask]
print(result)

#Mask breakdown

names == 'Bob'
# [ True False False  True False False]

names == 'Will'
# [False False  True False  True False]

#Using OR (|):
# -->  [ True False  True  True  True False]

#Result: [85 78 88 95]

#3️⃣ Find all scores less than 80 and set them to 0
#This is in-place modification using a mask.

scores[scores < 80] = 0
print(scores)

#What happens internally

scores < 80

# Creates: --> [False False  True False False  True]

# Then NumPy assigns 0 where the mask is True.
# Result: --> [85 92  0 88 95  0]

#Why this is called “vectorized”

 #No loops.
 #No if statements.
 #NumPy does everything in parallel at C speed 🚀

#Mental model (remember this)
 #Comparison → boolean mask
 #Mask → selects or modifies data


[92 78 95 73]
[85 78 88 95]
[85 92  0 88 95  0]


array([False, False,  True, False, False,  True])

In [24]:

#Part 6: Universal Functions (ufuncs) and Methods

#Linear algebra operations, like matrix multiplication, are crucial for many data science algorithms.
#Multiplying two arrays with * is an element-wise product; for matrix multiplication, use .dot() or the @ operator.

# [DEMO] Matrix Multiplication
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[6, 23], [-1, 7], [8, 9]])

print("Matrix product (x @ y):\n", x @ y)


Matrix product (x @ y):
 [[ 28  64]
 [ 67 181]]


In [28]:
# -- Exercise 4 : Reshaping and Statistics

#Create an array of 15 integers using arange(15) and reshape it to (3, 5).
#Calculate the average value of each row.
#Use np.unique() to find distinct elements in an array of your choice.
#Transpose the reshaped array using .T and check the new shape.

#1️⃣ Create an array of 15 integers and reshape to (3, 5)

import numpy as np

arr = np.arange(15)
arr_reshaped = arr.reshape(3, 5)

print(arr_reshaped)
print(arr_reshaped.shape)

#2️⃣ Calculate the average (mean) value of each row

row_means = arr_reshaped.mean(axis=1)
print(row_means)
print(row_means.shape)

#3️⃣ Use np.unique() to find distinct elements

sample = np.array([4, 2, 7, 2, 4, 9, 7])
unique_values = np.unique(sample)

print(unique_values)

#4️⃣ Transpose the reshaped array and check the new shape

arr_T = arr_reshaped.T

print(arr_T)
print(arr_T.shape)



[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
[ 2.  7. 12.]
(3,)
[2 4 7 9]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
(5, 3)
